// ===== Pixel art procédural : tous les sprites sont dessinés par code =====

const sprites: Record<string, HTMLCanvasElement> = {};

function mk(rows: string[], pal: Record<string, string>): HTMLCanvasElement {
  const h = rows.length, w = rows[0].length;
  const c = document.createElement("canvas");
  c.width = w; c.height = h;
  const g = c.getContext("2d")!;
  for (let y = 0; y < h; y++)
    for (let x = 0; x < rows[y].length; x++) {
      const ch = rows[y][x];
      if (ch === "." || ch === " ") continue;
      const col = pal[ch];
      if (!col) continue;
      g.fillStyle = col;
      g.fillRect(x, y, 1, 1);
    }
  return c;
}

export function getSprite(name: string): HTMLCanvasElement { return sprites[name]; }

export function initSprites() {
  const O = "#141021"; // contour

  // ================= HÉROS =================
  sprites["player"] = mk([
    "......rr........",
    ".....rrr........",
    "....OhhhhO......",
    "...OhhhhhhO.....",
    "...OhDDDDhO.....",
    "...OhhhhhhO.....",
    "..OaaaaaaaaO....",
    ".OwaALLALAawO...",
    ".OwaAAAAAAawO.s.",
    ".OwaALggLAawO.s.",
    "..OaAAAAAAaO.gs.",
    "...OaaaaaaO..Os.",
    "...OllOOllO.....",
    "...OllO.OllO....",
    "..ObbO...ObbO...",
    "................",
  ], {
    r: "#c23b3b", h: "#9ba8c2", D: "#232032", a: "#6b7a99", A: "#8b9ab8",
    L: "#a8b6d2", g: "#e0b13e", w: "#7c8aa8", l: "#3d4358", b: "#2b2f40",
    s: "#c8d2e8", O,
  });

  // ================= LE RIVAL (écho sombre du héros — même silhouette, palette inversée) =================
  sprites["rival"] = mk([
    "......rr........",
    ".....rrr........",
    "....OhhhhO......",
    "...OhhhhhhO.....",
    "...OhDDDDhO.....",
    "...OhhhhhhO.....",
    "..OaaaaaaaaO....",
    ".OwaALLALAawO...",
    ".OwaAAAAAAawO.s.",
    ".OwaALggLAawO.s.",
    "..OaAAAAAAaO.gs.",
    "...OaaaaaaO..Os.",
    "...OllOOllO.....",
    "...OllO.OllO....",
    "..ObbO...ObbO...",
    "................",
  ], {
    r: "#7a1a2a", h: "#2a2438", D: "#0c0a14", a: "#3a2a4e", A: "#4a3a62",
    L: "#5a4a76", g: "#ff2a3a", w: "#241c34", l: "#150f22", b: "#0c0818",
    s: "#8a3050", O: "#000000",
  });

  // ================= SLIME =================
  sprites["slime"] = mk([
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OgggggGO....",
    "...OgWWggggGO...",
    "..OgWWgggggggO..",
    "..OggggggggggO..",
    ".OggeeggggeeggO.",
    ".OggeeggggeeggO.",
    ".OgggggmmggggGO.",
    ".OggggggggggggO.",
    "..OggggggggggO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
  ], { g: "#54b357", G: "#3f8e46", W: "#b8e8b0", e: "#17311c", m: "#17311c", O });

  sprites["slime_2"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "....OOOOOOOO....",
    "...OgWWgggggO...",
    "..OgWWggggggGO..",
    ".OggggggggggggO.",
    ".OgeeggggggeegO.",
    ".OgeeggggggeegO.",
    "OggggggmmgggggGO",
    "OggggggggggggggO",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
  ], { g: "#54b357", G: "#3f8e46", W: "#b8e8b0", e: "#17311c", m: "#17311c", O });

  // ================= SLIME NOCTURNE =================
  const nightPal = { g: "#4b3f8f", G: "#352a66", W: "#8f7fd4", e: "#7ff0ff", m: "#0c0a1c", O };
  sprites["nightslime"] = mk([
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OgggggGO....",
    "...OgWWggggGO...",
    "..OgWWgggggggO..",
    "..OggggggggggO..",
    ".OggeeggggeeggO.",
    ".OggeeggggeeggO.",
    ".OgggggmmggggGO.",
    ".OggggggggggggO.",
    "..OggggggggggO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
  ], nightPal);
  sprites["nightslime_2"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "....OOOOOOOO....",
    "...OgWWgggggO...",
    "..OgWWggggggGO..",
    ".OggggggggggggO.",
    ".OgeeggggggeegO.",
    ".OgeeggggggeegO.",
    "OggggggmmgggggGO",
    "OggggggggggggggO",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
  ], nightPal);

  // ================= ARAIGNÉE DES CAVERNES =================
  sprites["spider"] = mk([
    "................",
    "................",
    "................",
    ".....OOOOOO.....",
    "....OgggggGO....",
    "...OgWWggggGO...",
    "l.OgWWgggggggO.l",
    "..OggggggggggO..",
    ".OggeeggggeeggO.",
    "lOggeeggggeeggOl",
    ".OgggggmmggggGO.",
    ".OggggggggggggO.",
    "..OggggggggggO..",
    "...OOOOOOOOOO...",
    "................",
    "................",
  ], { g: "#3a3244", G: "#241f2c", W: "#6a5f78", e: "#ff2a2a", m: "#1a1620", l: "#161018", O });

  // ================= GARGOUILLE ÉVEILLÉE =================
  sprites["gargoyle"] = mk([
    "................",
    "...OOOOOOOO.....",
    "..OrrRRRRrrO....",
    "..OrReeeeRrO....",
    "..OrReffeRrO....",
    "..OrReeeeRrO....",
    ".OOrrRRRRrrOO...",
    "OrrRRRRRRRRrrO..",
    "OrRRcCCcRRRRrO..",
    "OrRRcCCcRRRRrO..",
    "OrrRRRRRRRRrrO..",
    ".OrrRRRRRRrrO...",
    "..OrrO..OrrO....",
    "..OrrO..OrrO....",
    ".OrrrO..OrrrO...",
    "................",
  ], { r: "#4a5560", R: "#7a8a9a", e: "#3af0c8", f: "#8afff0", c: "#5fd442", C: "#3a9e2a", O });

  // ================= GOLEM =================
  sprites["golem"] = mk([
    "................",
    "...OOOOOOOO.....",
    "..OrrRRRRrrO....",
    "..OrReeeeRrO....",
    "..OrReffeRrO....",
    "..OrReeeeRrO....",
    ".OOrrRRRRrrOO...",
    "OrrRRRRRRRRrrO..",
    "OrRRcCCcRRRRrO..",
    "OrRRcCCcRRRRrO..",
    "OrrRRRRRRRRrrO..",
    ".OrrRRRRRRrrO...",
    "..OrrO..OrrO....",
    "..OrrO..OrrO....",
    ".OrrrO..OrrrO...",
    "................",
  ], {
    r: "#5c544a", R: "#8a7f72", e: "#2b2620", f: "#ff9d2e",
    c: "#ffb347", C: "#ff8c1a", O,
  });

  // ================= GARDIEN DES SCEAUX =================
  sprites["warden"] = mk([
    ".t....OOOO....t.",
    ".tt.OppppppO.tt.",
    "..tOpPPPPPPpOt..",
    "..OpPeePPeePpO..",
    "..OpPEePPeEPpO..",
    ".OppmmmmmmmmppO.",
    "OpPPPPPPPPPPPPpO",
    "OpPPgPPPPPPgPPpO",
    "OpPPPPPPPPPPPPpO",
    "OpPPgPPPPPPgPPpO",
    "OppPPPPPPPPPPppO",
    ".OpPPPPPPPPPPpO.",
    ".OppppppppppppO.",
    "..OOtOOOOOOtOO..",
    "...t........t...",
    "................",
  ], {
    p: "#2c1650", P: "#4a2f8a", e: "#ff3030", E: "#ff7a50",
    m: "#150b2e", g: "#d4b6ff", t: "#d8cfc0", O,
  });

  // ================= ROI DE L'ABÎME (24x24) =================
  sprites["boss"] = mk([
    "..BB................BB..",
    "...BB..............BB...",
    "....Bb............bB....",
    ".....Bb.OhhhhhhO..bB....",
    "......BOhHHHHHHhOB......",
    "......OhHeeHHeeHhO......",
    "......OhEeeHHeeEhO......",
    "......OhHHHHHHHHhO......",
    "......OhMttttttMhO......",
    "......OhMmmmmmMhO.......",
    ".......OhhhhhhhhO.......",
    "....OrrrrrrrrrrrrrrO..s.",
    "...OrrRRRRRRRRRRRRrrO.s.",
    "...OrRRgRRRRRRRRgRRrO.s.",
    "...OrRRRRRRRRRRRRRRrO.s.",
    "...OrRRgRRRRRRRRgRRrO.s.",
    "...OrRRRRRRRRRRRRRRrOgsg",
    "....OrrRRRRRRRRRRrrO..g.",
    "....OrrrRRRRRRRRrrrO....",
    ".....Orr.rrRRrr.rrO.....",
    ".....Or...rrrr...rO.....",
    "..........rr............",
    "....E......gg......E....",
    "........................",
  ], {
    B: "#7a6f60", b: "#cfc4b0", h: "#2c2440", H: "#463a60",
    e: "#ff2020", E: "#ff6a50", t: "#e8e0d0", M: "#1a0f22", m: "#0c0614",
    r: "#1d1730", R: "#322447", g: "#b06aff", s: "#b8c4e0", O,
  });

  // ================= LORE : pierre gravée (inscriptions) =================
  sprites["lore_rune"] = mk([
    "................",
    "................",
    "...OOOOOOOO.....",
    "..OssssssssO....",
    "..OsRsssRssO....",
    "..OssRsRsssO....",
    "..OsRsssRssO....",
    "..OssssssssO....",
    "..OsRsRsRssO....",
    "..OssssssssO....",
    "..OsssRssssO....",
    "..OOOOOOOOOO....",
    "...hhhhhhhh.....",
    "................",
    "................",
    "................",
  ], { s: "#3a3448", R: "#9a6fe0", h: "#241f30", O: "#1a1622" });

  // ================= LORE : lame brisée du Rival =================
  sprites["rival_blade"] = mk([
    "................",
    "................",
    ".........bB.....",
    "........bB......",
    ".......Bb.......",
    "......bB........",
    ".....Bb.........",
    "....bB..........",
    "...cc...........",
    "..hCCh..........",
    "...hh...........",
    "...hh...........",
    "..r.r...........",
    ".r...r..........",
    "................",
    "................",
  ], { b: "#8a90a0", B: "#c8d0e0", c: "#5a4a30", C: "#8a7040", h: "#3a2c18", r: "#5a1820" });

  // ================= DÉCOR (PROPS) =================
  sprites["prop_torch"] = mk([
    ".......ff.......",
    "......fFFf......",
    "......fFFf......",
    ".......FF.......",
    ".......hh.......",
    "......ohho......",
    ".......hh.......",
    ".......hh.......",
    ".......hh.......",
    "......ohho......",
    ".......hh.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { f: "#ff9d2e", F: "#ffd84a", h: "#5a4028", o: "#3a2818" });
  sprites["prop_bones"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..WW....W..W....",
    ".W..W..WWWWW....",
    ".WWWW...W..W....",
    "....W...........",
    "..W.W..W.W.W....",
    ".WWW...WWWWW....",
    "................",
    "................",
    "................",
    "................",
  ], { W: "#b8b0a0" });
  sprites["prop_column"] = mk([
    "....cccccc....",
    "...cCCCCCCc...",
    "....cCCCCc....",
    "....CC..CC....",
    "....CC..CC....",
    "....CC..CC....",
    "....CC..CC....",
    "....CC..CC....",
    "....CC..CC....",
    "....CC..CC....",
    "....CCCCCC....",
    "...cCCCCCCc...",
    "..cccccccccc..",
    "................",
    "................",
    "................",
  ], { c: "#3a3444", C: "#524a5e" });
  sprites["prop_cobweb"] = mk([
    "w..............",
    ".w.....w.......",
    "..w...w........",
    "...w.w....w....",
    "....w....w.....",
    "...w.w..w......",
    "..w...ww.......",
    ".w....w.w......",
    "w....w...w.....",
    ".............. ",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { w: "#6a6478" });
  sprites["prop_puddle"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....ppppp.......",
    "...pPPPPPp......",
    "..pPPWPPPPp.....",
    "...pPPPPPp......",
    "....ppppp.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { p: "#1e2838", P: "#2e3a50", W: "#4a5a72" });
  sprites["prop_skull"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "......WWWW......",
    ".....WWWWWW.....",
    ".....WoWWoW.....",
    ".....WWWWWW.....",
    "......WooW......",
    ".....W.WW.W.....",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { W: "#c8c0b0", o: "#1a1620" });

  // ================= PIÈGES DU LABYRINTHE =================
  sprites["trap_spikes"] = mk([
    "................",
    ".OOOOOOOOOOOOOO.",
    ".O............O.",
    ".O.s..s..s..s.O.",
    ".O............O.",
    ".O.s..s..s..s.O.",
    ".O............O.",
    ".O.s..s..s..s.O.",
    ".O............O.",
    ".O.s..s..s..s.O.",
    ".O............O.",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
    "................",
    "................",
  ], { s: "#4a4048", O: "#2a2430" });
  sprites["trap_spikes_on"] = mk([
    "................",
    "..W..W..W..W.W..",
    ".WW.WW.WW.WW.WW.",
    ".SW.SW.SW.SW.SW.",
    ".SS.SS.SS.SS.SS.",
    ".OOOOOOOOOOOOOO.",
    ".OrOOrOOrOOrOOO.",
    ".O............O.",
    ".OOrOOOrOOOrOOO.",
    ".O............O.",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { W: "#c8c0cc", S: "#8a8490", r: "#a02030", O: "#2a2430" });
  sprites["trap_gas"] = mk([
    "................",
    "................",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { O: "#242a24" });
  sprites["trap_gas_on"] = mk([
    "......gg.g......",
    ".g..ggGGgg..g...",
    "..gGGGGGGGGg....",
    ".gGGWGGGGWGGg...",
    "..gGGGGGGGGg.g..",
    "...gggGGggg.....",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "..O.O.O.O.O.OO..",
    "..OOOOOOOOOOOO..",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { g: "#4a7a3a", G: "#6aa84a", W: "#a8e888", O: "#242a24" });

  // ================= CONSOMMABLES DE COMBAT =================
  sprites["it_bomb"] = mk([
    "................",
    "........f.......",
    ".......fF.......",
    "......ss........",
    ".....OssO.......",
    "....ObbbbO......",
    "...ObbBBbbO.....",
    "...ObBBBBbO.....",
    "...ObBBWBbO.....",
    "...ObBBBBbO.....",
    "...ObbBBbbO.....",
    "....ObbbbO......",
    ".....OOOO.......",
    "................",
    "................",
    "................",
  ], { b: "#2a2a34", B: "#3c3c4a", W: "#6a6a80", s: "#8a6a3a", f: "#ff9d2e", F: "#ffd84a", O });

  sprites["it_mist"] = mk([
    "................",
    "......OOO.......",
    "......OcO.......",
    ".....OOOOO......",
    ".....ObbbO......",
    "....ObmmmbO.....",
    "...ObmMMMmbO....",
    "...ObmMWMmbO....",
    "...ObmMMMmbO....",
    "...ObmmmmmbO....",
    "....ObbbbbO.....",
    ".....OOOOO......",
    "................",
    "................",
    "................",
    "................",
  ], { b: "#4a6a8a", m: "#7aa8c8", M: "#a8d0e8", W: "#e0f4ff", c: "#c8a05a", O });

  sprites["it_scroll"] = mk([
    "................",
    "................",
    "....OOOOOOOO....",
    "...OppPPPPppO...",
    "...OpPWWWWPpO...",
    "...OpPWrrWPpO...",
    "...OpPWWWWPpO...",
    "...OpPWrWWPpO...",
    "...OpPWWWWPpO...",
    "...OppPPPPppO...",
    "....OOOOOOOO....",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { p: "#8a6a3a", P: "#c8a05a", W: "#e8dcc0", r: "#a02838", O });

  // ================= DÉVOREUR D'ÂMES (super-boss post-jeu, 24x24) =================
  sprites["avatar"] = mk([
    "..BB................BB..",
    "...BB..............BB...",
    "....Bb............bB....",
    ".....Bb.OhhhhhhO..bB....",
    "......BOhHHHHHHhOB......",
    "......OhHeeHHeeHhO......",
    "......OhEeeHHeeEhO......",
    "......OhHHHHHHHHhO......",
    "......OhMttttttMhO......",
    "......OhMmmmmmMhO.......",
    ".......OhhhhhhhhO.......",
    "....OrrrrrrrrrrrrrrO..s.",
    "...OrrRRRRRRRRRRRRrrO.s.",
    "...OrRRgRRRRRRRRgRRrO.s.",
    "...OrRRRRRRRRRRRRRRrO.s.",
    "...OrRRgRRRRRRRRgRRrO.s.",
    "...OrRRRRRRRRRRRRRRrOgsg",
    "....OrrRRRRRRRRRRrrO..g.",
    "....OrrrRRRRRRRRrrrO....",
    ".....Orr.rrRRrr.rrO.....",
    ".....Or...rrrr...rO.....",
    "..........rr............",
    "....E......gg......E....",
    "........................",
  ], {
    B: "#4a3f52", b: "#8a7a95", h: "#160a1a", H: "#2e1830",
    e: "#ffffff", E: "#9ff2ff", t: "#e8e0d0", M: "#0e0512", m: "#050208",
    r: "#2a0a12", R: "#481523", g: "#ff3040", s: "#9aa8c8", O,
  });

  sprites["it_abysskey"] = mk([
    "................",
    "................",
    "......rr........",
    ".....OrrO.......",
    "....Op..pO......",
    "....Op..pO......",
    ".....OppO.......",
    "......Op........",
    "......Op........",
    "......Opp.......",
    "......Op........",
    "......Opp.......",
    "................",
    "................",
    "................",
    "................",
  ], { p: "#6a2f8a", r: "#ff3040", O });

  // ================= MARCHAND =================
  sprites["merchant"] = mk([
    "................",
    "....OOOOOO......",
    "...OmmmmmmO.....",
    "..OmmMMMMmmO....",
    "..OmMffffMmO....",
    "..OmMfeefMmO....",
    "..OmMffffMmO....",
    "..OmmMMMMmmO....",
    ".OmmRRRRRRmmO...",
    ".OmRRgRRgRRmOp..",
    ".OmRRRRRRRRmpp..",
    ".OmRRRRRRRRmpP..",
    ".OmmRRRRRRmmOp..",
    "..OllO..OllO....",
    "..ObbO..ObbO....",
    "................",
  ], {
    m: "#7a5a30", M: "#b58a4e", f: "#d8a878", e: "#2b2018",
    R: "#8a6838", g: "#e0b13e", l: "#4a3820", b: "#2e2214",
    p: "#c8a05a", P: "#e0b13e", O,
  });

  // ================= PNJ =================
  const villager = (tunic: string, tunic2: string, hair: string) => mk([
    "................",
    ".....OOOO.......",
    "....OqqqqO......",
    "...OqqqqqqO.....",
    "...OffffffO.....",
    "...OfeffefO.....",
    "...OffffffO.....",
    "....OffffO......",
    "..OttTTTTttO....",
    ".OwtTTTTTTtwO...",
    ".OwtTTTTTTtwO...",
    ".OwtTTTTTTtwO...",
    "..OttTTTTttO....",
    "...OllOOllO.....",
    "...ObbO.ObbO....",
    "................",
  ], { q: hair, f: "#d8a878", e: "#2b2018", t: tunic, T: tunic2, w: "#c89868", l: "#3d3448", b: "#282234", O });

  sprites["pnj_kael"] = villager("#7a3c2e", "#a05540", "#4a3828");
  sprites["pnj_lysa"] = villager("#3c5a7a", "#5a80a8", "#c8a050");
  sprites["pnj_orin"] = villager("#4a6038", "#688850", "#787060");
  sprites["pnj_elya"] = villager("#6a3c6a", "#95589a", "#382828");
  sprites["pnj_vesna"] = villager("#8a6838", "#b58a4e", "#583c20");

  // Sentinelle (garde en armure avec lance)
  sprites["pnj_sentinelle"] = mk([
    "..l.............",
    "..l..OOOO.......",
    "..L.OhhhhO......",
    "..l.OhDDhhO.....",
    "..l.OhhhhhO.....",
    "..lOaaaaaaaO....",
    "..lOaAAAAAaO....",
    "..lwaAgAgAaw....",
    "..lwaAAAAAaw....",
    "..lOaAAAAAaO....",
    "..lOaaaaaaaO....",
    "..l.OllOllO.....",
    "..l.OllOllO.....",
    "..lObbO.ObbO....",
    "..l.............",
    "................",
  ], {
    h: "#8a94ac", D: "#232032", a: "#5c6880", A: "#7c88a2", g: "#e0b13e",
    w: "#6c7890", l: "#8a7448", L: "#c8c8d8", b: "#2b2f40", O,
  });

  // ================= COFFRES =================
  sprites["chest"] = mk([
    "................",
    "................",
    "................",
    "................",
    "...OOOOOOOOOO...",
    "..OwwwwwwwwwwO..",
    ".OwWWWWWWWWWWwO.",
    ".OwwwwgGgwwwwwO.",
    ".OOOOOOOOOOOOOO.",
    ".OwWWWWgWWWWWwO.",
    ".OwwwwwgGwwwwwO.",
    ".OwWWWWgWWWWWwO.",
    ".OwwwwwwwwwwwwO.",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
  ], { w: "#8a5a2b", W: "#a8743c", g: "#e0b13e", G: "#f8d878", O });

  sprites["chest_open"] = mk([
    "................",
    "................",
    ".OOOOOOOOOOOOOO.",
    ".OwWWWWWWWWWWwO.",
    ".OwwwwwwwwwwwwO.",
    ".OOOOOOOOOOOOOO.",
    ".Odd?ddddd?dddO.",
    ".OddddddddddddO.",
    ".OOOOOOOOOOOOOO.",
    ".OwWWWWgWWWWWwO.",
    ".OwwwwwgGwwwwwO.",
    ".OwWWWWgWWWWWwO.",
    ".OwwwwwwwwwwwwO.",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
  ], { w: "#8a5a2b", W: "#a8743c", g: "#e0b13e", G: "#f8d878", d: "#241a10", "?": "#48381f", O });

  sprites["chest_leg"] = mk([
    "................",
    "................",
    "......gg........",
    ".....gGGg.......",
    "...OOOOOOOOOO...",
    "..OppppppppppO..",
    ".OpPPPPPPPPPPpO.",
    ".OpppppgGgppppO.",
    ".OOOOOOOOOOOOOO.",
    ".OpPPPPgPPPPPpO.",
    ".OpppppgGpppppO.",
    ".OpPPPPgPPPPPpO.",
    ".OppppppppppppO.",
    ".OOOOOOOOOOOOOO.",
    "................",
    "................",
  ], { p: "#4a2f80", P: "#6b46b8", g: "#e0b13e", G: "#f8d878", O });

  // ================= OBJETS =================
  sprites["it_sword"] = mk([
    "................",
    "..........O.....",
    ".........OsO....",
    "........OsSO....",
    ".......OsSO.....",
    "......OsSO......",
    ".....OsSO.......",
    "....OsSO........",
    "...OgOO.........",
    "..OggO..........",
    ".OhOgO..........",
    ".OhhO...........",
    "..OO............",
    "................",
    "................",
    "................",
  ], { s: "#c8d2e8", S: "#8b9ab8", g: "#e0b13e", h: "#6a4a28", O });

  sprites["it_legend"] = mk([
    "................",
    "..........O.....",
    ".....*...OsO....",
    "........OsSO....",
    ".......OsSO.*...",
    "..*...OsSO......",
    ".....OsSO.......",
    "....OsSO........",
    "...OgOO...*.....",
    "..OggO..........",
    ".OhOgO..........",
    ".OhhO...........",
    "..OO.....*......",
    "................",
    "................",
    "................",
  ], { s: "#ffe9a8", S: "#e0b13e", g: "#8a5fd0", h: "#4a2f80", "*": "#fff0c0", O });

  sprites["it_armor"] = mk([
    "................",
    "................",
    "................",
    "...OO.....OO....",
    "..OaaO...OaaO...",
    "..OaAOOOOOAaO...",
    "..OaAAAAAAAaO...",
    "...OAAgAgAAO....",
    "...OAAAAAAAO....",
    "...OAAgAgAAO....",
    "...OaAAAAAaO....",
    "....OaaaaaO.....",
    ".....OOOOO......",
    "................",
    "................",
    "................",
  ], { a: "#6b7a99", A: "#8b9ab8", g: "#e0b13e", O });

  sprites["it_gem"] = mk([
    "................",
    "................",
    "................",
    "................",
    "......OOOO......",
    ".....OrRRrO.....",
    "....OrRWWRrO....",
    "....OrRWRRrO....",
    "....OrRRRRrO....",
    ".....OrRRrO.....",
    "......OrrO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
  ], { r: "#a02838", R: "#e04858", W: "#ffb8c0", O });

  sprites["it_charm"] = mk([
    "................",
    "................",
    "......OOO.......",
    ".....O...O......",
    ".....O...O......",
    "......OOO.......",
    ".....OgggO......",
    "....OgGGGgO.....",
    "....OgGsGgO.....",
    "....OgGGGgO.....",
    ".....OgggO......",
    "......OOO.......",
    "................",
    "................",
    "................",
    "................",
  ], { g: "#c09030", G: "#e0b13e", s: "#fff0c0", O });

  sprites["it_ring"] = mk([
    "................",
    "................",
    "................",
    "................",
    "......rr........",
    ".....OrrO.......",
    "....OO..OO......",
    "...Og....gO.....",
    "...Og....gO.....",
    "...Og....gO.....",
    "....OO..OO......",
    ".....OggO.......",
    "................",
    "................",
    "................",
    "................",
  ], { g: "#e0b13e", r: "#e04858", O });

  sprites["it_torch"] = mk([
    "................",
    "......ff........",
    ".....ffFf.......",
    ".....fFFf.......",
    "......Ff........",
    ".....OhhO.......",
    ".....OhhO.......",
    "......Oh........",
    "......Oh........",
    "......Oh........",
    "......Oh........",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { f: "#ff9d2e", F: "#ffd84a", h: "#6a4a28", O });

  sprites["it_sunrelic"] = mk([
    "................",
    ".......rr.......",
    ".......rr.......",
    ".......rr.......",
    ".......rr.......",
    "......RRRR......",
    ".....RRRRRR.....",
    ".rrrrRRWWRRrrrr.",
    ".rrrrRRWWRRrrrr.",
    ".....RRRRRR.....",
    "......RRRR......",
    ".......rr.......",
    ".......rr.......",
    ".......rr.......",
    ".......rr.......",
    "................",
  ], { r: "#c9932a", R: "#ffd84a", W: "#fff6c8" });

  sprites["it_echoshard"] = mk([
    "................",
    "........rr......",
    ".......rWWr.....",
    "......rWssWr....",
    ".....rWssssWr...",
    "....rWssWWssWr..",
    "...rWssWssWssWr.",
    "....rWssWWssWr..",
    ".....rWssssWr...",
    "......rWssWr....",
    ".......rWWr.....",
    "........rr......",
    "................",
    "................",
    "................",
    "................",
  ], { r: "#3a1030", W: "#7a2a58", s: "#e83a5a", O });

  sprites["it_abyssrelic"] = mk([
    "................",
    "................",
    "................",
    "................",
    "......OOOO......",
    ".....OpPPpO.....",
    "....OpPeePpO....",
    "....OpPPPPpO....",
    ".....OpPPpO.....",
    "......OppO......",
    ".......OO.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { p: "#3a1550", P: "#6a2f8a", e: "#e02040", O });

  sprites["it_lantern"] = mk([
    "................",
    "......OO........",
    ".....O..O.......",
    "....OOOOOO......",
    "....OgFFgO......",
    "....OgFFgO......",
    "....OgffgO......",
    "....OOOOOO......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { g: "#8a6838", F: "#ffd84a", f: "#ff9d2e", O });

  sprites["it_key"] = mk([
    "................",
    "................",
    "................",
    "................",
    "....OOO.........",
    "...Og.gO........",
    "...Og.gO........",
    "....OOOgggggg...",
    ".......g..g.g...",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ], { g: "#c8a05a", O });

  // ================= PORTES =================
  sprites["door_closed"] = mk([
    ".OOOOOOOOOOOOOO.",
    "OssOOOOOOOOOOssO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOgwWwwwWwwwOsO",
    "OsOgwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OsOwwWwwwWwwwOsO",
    "OssOOOOOOOOOOssO",
    ".OOOOOOOOOOOOOO.",
  ], { s: "#6c6478", w: "#6a4a28", W: "#7e5a34", g: "#c8a05a", O });

  sprites["door_open"] = mk([
    ".OOOOOOOOOOOOOO.",
    "OssOOOOOOOOOOssO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddDddddddDOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddDddddddDOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OsOddddddddddOsO",
    "OssOOOOOOOOOOssO",
    ".OOOOOOOOOOOOOO.",
  ], { s: "#6c6478", d: "#100c1a", D: "#1e1830", O });

  // ================= SOCLE (épée légendaire au sol) =================
  sprites["pedestal"] = mk([
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "....OOOOOOOO....",
    "...OsSSSSSSsO...",
    "...OsSSSSSSsO...",
    "....OssssssO....",
    "...OsSSSSSSsO...",
    "..OssssssssssO..",
    "..OOOOOOOOOOOO..",
    "................",
  ], { s: "#5c5468", S: "#787084", O });
}
